version: '3.6'
services:
  liquibase:
    container_name: liquibase-container
    restart: always
    build: 
      context: ./liquibase
      dockerfile: Dockerfile
    volumes:
      - ./liquibase/:/home/project/liquibase-container
    networks:
      - liquibase-container
          
            
networks:
  liquibase-container:
    external: true